default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: reactworkshop_development 

test:
  <<: *default
  database: reactworkshop_test

production:
  <<: *default
  database: reactworkshop_production
